//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donaciones.WPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Beneficiarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiarios()
        {
            this.Ordenes = new  ObservableCollection<Ordenes>();
        }
    
        public string BeneficiarioID { get; set; }
        public string Iglesia { get; set; }
        public string Contacto { get; set; }
        public string Direccion { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string CodigoPostal { get; set; }
        public string Pais { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual  ObservableCollection<Ordenes> Ordenes { get; set; }
    }
}
