//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donaciones.WPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class OrdenesDetalle
    {
        public int OrdenID { get; set; }
        public int ProductoID { get; set; }
        public decimal PrecioUnitario { get; set; }
        public short Cantidad { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
