//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donaciones.WPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes()
        {
            this.OrdenesDetalle = new  ObservableCollection<OrdenesDetalle>();
        }
    
        public int OrdenID { get; set; }
        public string BeneficiarioID { get; set; }
        public Nullable<System.DateTime> OrdenDate { get; set; }
        public Nullable<System.DateTime> FechaIngresada { get; set; }
        public Nullable<System.DateTime> FechaEntregada { get; set; }
    
        public virtual Beneficiarios Beneficiarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual  ObservableCollection<OrdenesDetalle> OrdenesDetalle { get; set; }
    }
}
