//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donaciones.WPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.OrdenesDetalle = new  ObservableCollection<OrdenesDetalle>();
        }
    
        public int ProductoID { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<decimal> CantidadPorUnidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public bool Descontinuado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual  ObservableCollection<OrdenesDetalle> OrdenesDetalle { get; set; }
    }
}
